name: canvas-syllabus-scraper
channels:
  - anaconda
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - python>=3.7
  - termcolor
  - requests
  - pandas
  - pip
  - pip:
    - canvasapi>=2.0.0
    - beautifulsoup4
